apiVersion: v1
kind: Service
metadata:
  name: helpr
  labels:
    app: helpr
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: flask
  selector:
    app: helpr
  type: LoadBalancer